services:

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.19.4-alpine
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '10'
    restart: always
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - s-network

  nginx:
    container_name: nginx
    restart: always
    ports:
      - "443:443"
      - "9443:9443"
      - "6006:6006"
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    networks:
      - s-network

volumes:
  portainer_data:

networks:
  s-network:
    external: true
