services:

  grafana:
    image: grafana/grafana-enterprise:12.0.0@sha256:d0feefe7922323e713772f19de73cf75188417c97b648e7e81e0232cac58db01
    container_name: grafana
    restart: always
    networks:
      - s-network
    volumes:
      - 'grafana_data:/var/lib/grafana'

volumes:
  grafana_data:

networks:
  s-network:
    external: true
