services:

  grafana:
    image: grafana/grafana-enterprise:11.6.1@sha256:2d64fc9fc6c281d0b69988aea4fce254aedd96f3235a6216df321564750da475
    container_name: grafana
    restart: always
    networks:
      - s-network
    volumes:
      - 'grafana_data:/var/lib/grafana'

volumes:
  grafana_data:

networks:
  s-network:
    external: true
