services:

  grafana:
    image: grafana/grafana-enterprise:11.5.1@sha256:098749567519a97ddee6394921027a8888ce5afa14896010b4ce10407b7f9147
    container_name: grafana
    restart: always
    networks:
      - s-network
    volumes:
      - 'grafana_data:/var/lib/grafana'

volumes:
  grafana_data:

networks:
  s-network:
    external: true
