services:

  grafana:
    image: grafana/grafana-enterprise:10.4.10@sha256:a079b2d80132ae2f429c22e2b18b9e0c76a83b9e72d30b59d4b205bcaf89d83e
    container_name: grafana
    restart: always
    networks:
      - s-network
    volumes:
      - 'grafana_data:/var/lib/grafana'

volumes:
  grafana_data:

networks:
  s-network:
    external: true
