services:

  grafana:
    image: grafana/grafana-enterprise:11.4.0@sha256:473a26e9ed1bef41abf2b8d85d0d810a9006534664d30dee7e92b03c9a9cccb2
    container_name: grafana
    restart: always
    networks:
      - s-network
    volumes:
      - 'grafana_data:/var/lib/grafana'

volumes:
  grafana_data:

networks:
  s-network:
    external: true
