rules: []
rulesConfigs: []
pages:
  - name: error_page
    url: https://private.s-hirano.com/error
resourceServers: []
clients:
  - name: config backups
    app_type: non_interactive
    cross_origin_auth: false
    cross_origin_authentication: false
    custom_login_page_on: true
    grant_types:
      - client_credentials
    is_first_party: true
    is_token_endpoint_ip_header_trusted: false
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 36000
      secret_encoded: false
    oidc_conformant: true
    refresh_token:
      expiration_type: non-expiring
      leeway: 0
      infinite_token_lifetime: true
      infinite_idle_token_lifetime: true
      token_lifetime: 31557600
      idle_token_lifetime: 2592000
      rotation_type: non-rotating
    sso_disabled: false
    token_endpoint_auth_method: client_secret_post
  - name: s-private
    allowed_clients: []
    allowed_logout_urls:
      - https://private.s-hirano.com
    app_type: spa
    callbacks:
      - https://private.s-hirano.com/api/auth/callback/auth0
    client_aliases: []
    cross_origin_auth: false
    cross_origin_authentication: false
    custom_login_page_on: true
    grant_types:
      - authorization_code
      - implicit
      - refresh_token
    is_first_party: true
    is_token_endpoint_ip_header_trusted: false
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 36000
      secret_encoded: false
    logo_uri: https://private.s-hirano.com/logo.png
    native_social_login:
      apple:
        enabled: false
      facebook:
        enabled: false
    oidc_conformant: true
    refresh_token:
      expiration_type: expiring
      leeway: 0
      token_lifetime: 2592000
      idle_token_lifetime: 1296000
      infinite_token_lifetime: false
      infinite_idle_token_lifetime: false
      rotation_type: rotating
    sso_disabled: false
    token_endpoint_auth_method: none
    web_origins:
      - https://private.s-hirano.com
databases:
  - name: Username-Password-Authentication
    strategy: auth0
    enabled_clients:
      - config backups
      - s-private
    is_domain_connection: false
    options:
      mfa:
        active: true
        return_enroll_settings: true
      import_mode: false
      customScripts:
        change_password: ./databases/Username-Password-Authentication/change_password.js
        create: ./databases/Username-Password-Authentication/create.js
        delete: ./databases/Username-Password-Authentication/delete.js
        get_user: ./databases/Username-Password-Authentication/get_user.js
        login: ./databases/Username-Password-Authentication/login.js
        verify: ./databases/Username-Password-Authentication/verify.js
      disable_signup: true
      passwordPolicy: good
      passkey_options:
        challenge_ui: both
        local_enrollment_enabled: true
        progressive_enrollment_enabled: true
      password_history:
        size: 5
        enable: false
      strategy_version: 2
      password_dictionary:
        enable: false
        dictionary: []
      authentication_methods:
        passkey:
          enabled: false
        password:
          enabled: true
      brute_force_protection: true
      password_no_personal_info:
        enable: false
      password_complexity_options:
        min_length: 8
      enabledDatabaseCustomization: false
    realms:
      - Username-Password-Authentication
connections: []
tenant:
  enabled_locales:
    - en
  flags:
    revoke_refresh_token_grant: false
    disable_clickjack_protection_headers: false
  friendly_name: s-private
  oidc_logout:
    rp_logout_end_session_endpoint_discovery: true
  picture_url: https://private.s-hirano.com/logo.png
  sandbox_version: '18'
  support_email: s-hirano-ist@outlook.com
  support_url: https://private.s-hirano.com
  universal_login:
    colors:
      page_background: '#A7D8E3'
      primary: '#A7D8E3'
emailProvider: {}
emailTemplates: []
clientGrants: []
guardianFactors:
  - name: duo
    enabled: false
  - name: email
    enabled: false
  - name: otp
    enabled: false
  - name: push-notification
    enabled: false
  - name: recovery-code
    enabled: false
  - name: sms
    enabled: false
  - name: webauthn-platform
    enabled: false
  - name: webauthn-roaming
    enabled: false
guardianFactorProviders: []
guardianFactorTemplates: []
guardianPolicies:
  policies: []
guardianPhoneFactorSelectedProvider:
  provider: auth0
guardianPhoneFactorMessageTypes:
  message_types: []
roles:
  - name: dumper
    description: Dumper admin permission
    permissions: []
  - name: viewer
    description: Viewer admin permission
    permissions: []
branding:
  colors:
    page_background: '#A7D8E3'
    primary: '#A7D8E3'
  logo_url: https://private.s-hirano.com/logo.png
  templates: []
prompts:
  customText:
    en:
      login:
        login:
          title: s-private
          description: Contents dumper and viewer for s-hirano-ist
      login-id:
        login-id:
          title: s-private
          description: Contents dumper and viewer for s-hirano-ist
  identifier_first: true
  partials: {}
  universal_login_experience: new
  webauthn_platform_first_factor: false
actions:
  - name: fetch-role
    code: ./actions/fetch-role/code.js
    dependencies: []
    deployed: true
    runtime: node18-actions
    secrets: []
    status: built
    supported_triggers:
      - id: post-login
        version: v3
triggers:
  post-login:
    - action_name: fetch-role
      display_name: fetch-role
organizations: []
attackProtection:
  breachedPasswordDetection:
    enabled: false
    shields: []
    admin_notification_frequency: []
    method: standard
    stage:
      pre-user-registration:
        shields: []
  bruteForceProtection:
    enabled: true
    shields:
      - block
      - user_notification
    mode: count_per_identifier_and_ip
    allowlist: []
    max_attempts: 10
  suspiciousIpThrottling:
    enabled: true
    shields:
      - admin_notification
      - block
    allowlist: []
    stage:
      pre-login:
        max_attempts: 100
        rate: 864000
      pre-user-registration:
        max_attempts: 50
        rate: 1200
logStreams: []
customDomains: []
themes:
  - borders:
      button_border_weight: 1
      buttons_style: rounded
      button_border_radius: 3
      input_border_weight: 1
      inputs_style: rounded
      input_border_radius: 3
      widget_corner_radius: 5
      widget_border_weight: 0
      show_widget_shadow: true
    colors:
      primary_button: '#A7D8E3'
      primary_button_label: '#ffffff'
      secondary_button_border: '#c9cace'
      secondary_button_label: '#1e212a'
      base_focus_color: '#A7D8E3'
      base_hover_color: '#000000'
      links_focused_components: '#A7D8E3'
      header: '#1e212a'
      body_text: '#1e212a'
      widget_background: '#ffffff'
      widget_border: '#c9cace'
      input_labels_placeholders: '#65676e'
      input_filled_text: '#000000'
      input_border: '#c9cace'
      input_background: '#ffffff'
      icons: '#A7D8E3'
      error: '#d03c38'
      success: '#A7D8E3'
      captcha_widget_theme: light
    displayName: Unnamed Theme
    fonts:
      font_url: ''
      reference_text_size: 16
      title:
        bold: false
        size: 150
      subtitle:
        bold: false
        size: 87.5
      body_text:
        bold: false
        size: 87.5
      buttons_text:
        bold: false
        size: 100
      input_labels:
        bold: false
        size: 100
      links:
        bold: true
        size: 87.5
      links_style: normal
    page_background:
      page_layout: center
      background_color: '#A7D8E3'
      background_image_url: ''
    widget:
      logo_position: center
      logo_url: https://private.s-hirano.com/logo.png
      logo_height: 52
      header_text_alignment: center
      social_buttons_layout: bottom
forms: []
flows: []
flowVaultConnections: []
selfServiceProfiles: []
