rules: []
rulesConfigs: []
pages:
  - name: error_page
    url: https://private.s-hirano.com/error
resourceServers: []
clients:
  - name: config backups
    app_type: non_interactive
    cross_origin_auth: false
    cross_origin_authentication: false
    custom_login_page_on: true
    grant_types:
      - client_credentials
    is_first_party: true
    is_token_endpoint_ip_header_trusted: false
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 36000
      secret_encoded: false
    oidc_conformant: true
    refresh_token:
      expiration_type: non-expiring
      leeway: 0
      infinite_token_lifetime: true
      infinite_idle_token_lifetime: true
      token_lifetime: 31557600
      idle_token_lifetime: 2592000
      rotation_type: non-rotating
    sso_disabled: false
    token_endpoint_auth_method: client_secret_post
  - name: s-private
    allowed_clients: []
    allowed_logout_urls:
      - https://private.s-hirano.com
    app_type: spa
    callbacks:
      - https://private.s-hirano.com/api/auth/callback/auth0
    client_aliases: []
    cross_origin_auth: false
    cross_origin_authentication: false
    custom_login_page_on: true
    grant_types:
      - authorization_code
      - implicit
      - refresh_token
    is_first_party: true
    is_token_endpoint_ip_header_trusted: false
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 36000
      secret_encoded: false
    logo_uri: ''
    native_social_login:
      apple:
        enabled: false
      facebook:
        enabled: false
    oidc_conformant: true
    refresh_token:
      expiration_type: expiring
      leeway: 0
      token_lifetime: 2592000
      idle_token_lifetime: 1296000
      infinite_token_lifetime: false
      infinite_idle_token_lifetime: false
      rotation_type: rotating
    sso_disabled: false
    token_endpoint_auth_method: none
    web_origins:
      - https://private.s-hirano.com
databases:
  - name: Username-Password-Authentication
    strategy: auth0
    enabled_clients:
      - config backups
      - s-private
    is_domain_connection: false
    options:
      mfa:
        active: true
        return_enroll_settings: true
      import_mode: false
      customScripts:
        change_password: ./databases/Username-Password-Authentication/change_password.js
        create: ./databases/Username-Password-Authentication/create.js
        delete: ./databases/Username-Password-Authentication/delete.js
        get_user: ./databases/Username-Password-Authentication/get_user.js
        login: ./databases/Username-Password-Authentication/login.js
        verify: ./databases/Username-Password-Authentication/verify.js
      disable_signup: true
      passwordPolicy: good
      passkey_options:
        challenge_ui: both
        local_enrollment_enabled: true
        progressive_enrollment_enabled: true
      password_history:
        size: 5
        enable: false
      strategy_version: 2
      password_dictionary:
        enable: false
        dictionary: []
      authentication_methods:
        passkey:
          enabled: false
        password:
          enabled: true
      brute_force_protection: true
      password_no_personal_info:
        enable: false
      password_complexity_options:
        min_length: 8
      enabledDatabaseCustomization: false
    realms:
      - Username-Password-Authentication
connections:
  - name: google-oauth2
    strategy: google-oauth2
    enabled_clients: []
    is_domain_connection: false
    options:
      email: true
      scope:
        - email
        - profile
      profile: true
tenant:
  enabled_locales:
    - en
  flags:
    revoke_refresh_token_grant: false
    disable_clickjack_protection_headers: false
  friendly_name: s-private
  oidc_logout:
    rp_logout_end_session_endpoint_discovery: true
  picture_url: https://private.s-hirano.com/logo.png
  sandbox_version: '18'
  support_email: s-hirano-ist@outlook.com
  support_url: https://private.s-hirano.com
emailProvider: {}
emailTemplates: []
clientGrants: []
guardianFactors:
  - name: duo
    enabled: false
  - name: email
    enabled: false
  - name: otp
    enabled: false
  - name: push-notification
    enabled: false
  - name: recovery-code
    enabled: false
  - name: sms
    enabled: false
  - name: webauthn-platform
    enabled: false
  - name: webauthn-roaming
    enabled: false
guardianFactorProviders: []
guardianFactorTemplates: []
guardianPolicies:
  policies: []
guardianPhoneFactorSelectedProvider:
  provider: auth0
guardianPhoneFactorMessageTypes:
  message_types: []
roles:
  - name: dumper
    description: Dumper admin permission
    permissions: []
  - name: viewer
    description: Viewer admin permission
    permissions: []
branding:
  logo_url: https://private.s-hirano.com/logo.png
  templates: []
prompts:
  customText: {}
  partials: {}
  universal_login_experience: new
actions:
  - name: fetch-role
    code: ./actions/fetch-role/code.js
    dependencies: []
    deployed: true
    runtime: node18-actions
    secrets: []
    status: built
    supported_triggers:
      - id: post-login
        version: v3
triggers:
  post-login:
    - action_name: fetch-role
      display_name: fetch-role
organizations: []
attackProtection:
  breachedPasswordDetection:
    enabled: false
    shields: []
    admin_notification_frequency: []
    method: standard
    stage:
      pre-user-registration:
        shields: []
  bruteForceProtection:
    enabled: true
    shields:
      - block
      - user_notification
    mode: count_per_identifier_and_ip
    allowlist: []
    max_attempts: 10
  suspiciousIpThrottling:
    enabled: true
    shields:
      - admin_notification
      - block
    allowlist: []
    stage:
      pre-login:
        max_attempts: 100
        rate: 864000
      pre-user-registration:
        max_attempts: 50
        rate: 1200
logStreams: []
customDomains: []
themes: []
forms: []
flows: []
flowVaultConnections: []
selfServiceProfiles: []
