services:

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.21.0-alpine
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '10'
    restart: always
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - s-network

volumes:
  portainer_data:

networks:
  s-network:
    external: true
