services:

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.25.1-alpine@sha256:6a1389b662e8fd6475878be039fe336fa1cbd65dae7909564a80ff5dde797660
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '10'
    restart: always
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - s-network

volumes:
  portainer_data:

networks:
  s-network:
    external: true
