services:

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.26.1-alpine@sha256:b18469aeb498c2342e021b5c5cdefc6730ffe2b047bb6b508fa835bd2b1f7bc8
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '10'
    restart: always
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - s-network

volumes:
  portainer_data:

networks:
  s-network:
    external: true
