services:

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.23.0-alpine@sha256:97342cf8a821d64d59880bdede8f45ea9c869fea702dd56128a67d552dc632ab
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '10'
    restart: always
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - s-network

volumes:
  portainer_data:

networks:
  s-network:
    external: true
