services:

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.27.1-alpine@sha256:1465f22798cfb5d0a014847ce2c1b750d56588b2dcbb7eb4e03671ad46dd1c71
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '10'
    restart: always
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - s-network

volumes:
  portainer_data:

networks:
  s-network:
    external: true
