services:

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.25.0-alpine@sha256:6367d36f15ea50a2f2d042f3671b5b0f279f447a1d1a270ae0e6a07c1f062e41
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '10'
    restart: always
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - s-network

volumes:
  portainer_data:

networks:
  s-network:
    external: true
