services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.9.0@sha256:c99d7ee4d12a38661788f60d9eca493f08584e2e544bbd3b3fca64749f86b848
    container_name: node_exporter
    restart: always
    volumes:
      - '/:/host:ro,rslave'
    networks:
      - s-network

networks:
  s-network:
    external: true
