services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.8.2@sha256:4032c6d5bfd752342c3e631c2f1de93ba6b86c41db6b167b9a35372c139e7706
    container_name: node_exporter
    restart: always
    volumes:
      - '/:/host:ro,rslave'
    networks:
      - s-network

networks:
  s-network:
    external: true
