services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.9.1@sha256:d00a542e409ee618a4edc67da14dd48c5da66726bbd5537ab2af9c1dfc442c8a
    container_name: node_exporter
    restart: always
    volumes:
      - '/:/host:ro,rslave'
    networks:
      - s-network

networks:
  s-network:
    external: true
