services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.7.0@sha256:4cb2b9019f1757be8482419002cb7afe028fdba35d47958829e4cfeaf6246d80
    container_name: node_exporter
    restart: always
    volumes:
      - '/:/host:ro,rslave'
    networks:
      - s-network

networks:
  s-network:
    external: true
