name: Renovate Config Validator

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/renovate.json5'
      - '.github/workflows/renovate-validator.yaml'

jobs:
  renovate-config-validator:
    timeout-minutes: 10
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: validate renovate.json
        run: npx --package=renovate -c renovate-config-validator
