name: Renovate Config Validator

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/renovate.json5'
      - '.github/workflows/renovate-validator.yaml'

jobs:
  renovate-config-validator:
    runs-on: ubuntu-24.04
    permissions: {}
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: validate renovate.json
        run: npx --package=renovate -c renovate-config-validator
